name: iOS

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Gluon's GraalVM
        uses: gluonhq/setup-graalvm@master
        with:
          graalvm: '22.1.0.1-Final'
          jdk: 'java17'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Gluon Build
        run: ./mvnw -Pios gluonfx:build gluonfx:package

