name: macOS AArch64

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Gluon's GraalVM
        uses: gluonhq/setup-graalvm@master
        with:
          graalvm: '22.1.0.1-Final'
          jdk: 'java17'
          arch: 'aarch64'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        

      - name: Gluon Build and Package
        id: outputfile
        run: |
          ./mvnw -Pdesktop,mac gluonfx:build gluonfx:package
          echo ::set-output name=path::target/gluonfx/aarch64-darwin/HelloGluon-1.0.0.pkg

     
